# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Auto Deploy Site

on:
  push:
    branches:
      - master

jobs:
  build:
    # 使用最新版ubantu虚拟机运行
    runs-on: ubuntu-latest

    steps:
      # from: https://github.com/actions/checkout
      - name: 本工作流
        uses: actions/checkout@master

      # 安装最新版 Node.js
      # from: https://github.com/actions/setup-node
      - name: 安装 Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: 安装 yarn
        run: |
          npm install yarn -g

      - name: 安装项目依赖
        run: |
          yarn install

      - name: 构建项目
        run: |
          yarn build

      - name: 部署到 ghpage
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          PUBLISH_BRANCH: ghpage
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false
          forceOrphan: true
